name: haschemell
version: 0.1.0.0
github: "pawelrubin/haschemell"
license: BSD3
author: "Paweł Rubin"
maintainer: "pawelrubin19@gmail.com"
copyright: "2020 Paweł Rubin"
synopsis: A little scheme compiler for the LLVM platform written in Haskell.
category: Compilers/Interpreters
description: Please see the README on GitHub at <https://github.com/pawelrubin/haschemell#readme>
extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - OverloadedStrings
  - LambdaCase
ghc-options: -Wall
  -fno-warn-name-shadowing
  -Wcompat
  -Wincomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - text
  - string-conversions
  - prettyprinter
  - pretty-simple
  - parsec
  - directory
  - llvm-hs-pure >= 9 && < 10
  - llvm-hs >= 9 && < 10
  - llvm-hs-pretty >= 0.9 && < 1
  - mtl
  - containers

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - optparse-applicative
    - haschemell

tests:
  haschemell-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - haschemell
